---
- block:
  - name: Add IP to private zone
    local_action:
      module: route53
      state: present
      zone: "{{ route53_zone }}"
      private_zone: yes
      record: "{{ route53_Arecord }}"
      type: A
      ttl: 1200
      value: "{{ ec2.tagged_instances[0].private_ip }}"
      overwrite: yes
      wait: yes

  - name: Add CNAMES to private zone
    local_action:
      module: route53
      state: present
      zone: "{{ route53_zone }}"
      private_zone: yes
      record: "{{ item }}.{{ route53_Arecord }}"
      type: CNAME
      overwrite: yes
      ttl: 3600
      value: "{{ route53_Arecord }}"
    with_items:
    - "{{ route53_cnames }}"
  tags: 
  - route53:private