---
# tasks file for ansible-role-route53
- block:
  - include_tasks: public_zone.yml

  - include_tasks: aws_private_zone.yml
    when: 
    - aws_region is defined
    - aws_region is not none
  when: route53_subdomain is not none