---
- block:
  - name: Add IP to public zone
    local_action:
      module: route53
      state: present
      zone: "{{ route53_subdomain }}"
      record: "{{ route53_Arecord }}.{{ route53_subdomain }}"
      type: A
      ttl: 1200
      value: "{{ ansible_host }}"
      overwrite: yes
      wait: yes

  - name: Add CNAMES to public zone
    local_action:
      module: route53
      state: present
      zone: "{{ route53_subdomain }}"
      record: "{{ item }}.{{ route53_Arecord }}.{{ route53_subdomain }}"
      type: CNAME
      ttl: 3600
      overwrite: yes
      value: "{{ route53_Arecord }}.{{ route53_subdomain }}"
    with_items:
    - "{{ route53_cnames }}"
  tags: 
  - route53:public